### ISSUE TITLE
Recreate Progress bar

### ISSUE THREAD

**Issue by wlauer3** [Logan-Fouts/PicPurge#23]
- I may have royally messed up the code, but I fixed it to an older version prior to when the progress bar was made
- I hope this can be restored easily, if not I am so sorry

**Comment by wlauer3** [comment]
Made a progress bar that is at the bottom. Doesn't link to backend yet.

**Comment by Logan-Fouts** [comment]
It now links to the backend :+1:

**Comment by Logan-Fouts** [comment]
Should be able to close this issue now
